//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultsProbe
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label pLocalized;
        protected global::System.Web.UI.WebControls.Label pStyleLower;
        protected global::System.Web.UI.WebControls.Panel pStyleUpper;
        protected global::System.Web.UI.WebControls.Label pLabel;
        protected global::System.Web.UI.WebControls.TextBox pTextBox;
        protected global::System.Web.UI.WebControls.TextBox pTextArea;
        protected global::System.Web.UI.WebControls.TextBox pPassword;
        protected global::System.Web.UI.WebControls.Button pButton;
        protected global::System.Web.UI.WebControls.LinkButton pLinkButton;
        protected global::System.Web.UI.WebControls.HyperLink pHyperLink;
        protected global::System.Web.UI.WebControls.CheckBox pCheckBox;
        protected global::System.Web.UI.WebControls.Panel pPanel;
        protected global::System.Web.UI.WebControls.DropDownList pDropDown;
        protected global::System.Web.UI.WebControls.RadioButtonList pRadioV;
        protected global::System.Web.UI.WebControls.RadioButtonList pRadioH;
        protected global::System.Web.UI.WebControls.Label pExprSetting;
        protected global::System.Web.UI.WebControls.DataList pDataListVA;
        protected global::System.Web.UI.WebControls.GridView pGridPager;
        protected global::System.Web.UI.WebControls.HyperLink pHlImage;
        protected global::System.Web.UI.WebControls.CheckBoxList pCheckCols;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsProbe;
        protected global::System.Web.UI.WebControls.DataGrid pDataGrid;
        protected global::DefaultsProbe.FancyBadge pBadge;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pServerDiv;
        protected global::System.Web.UI.WebControls.Label pDivLabel;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow pServerRow;
        protected global::System.Web.UI.WebControls.GridView pGridDt;
        protected global::System.Web.UI.WebControls.Label pWrapped;
        protected global::System.Web.UI.WebControls.Label pResource;
        protected global::DefaultsProbe.FancyPanel pFancyPanel;
        protected global::DefaultsProbe.FancyLink pFancyLink;
        protected global::System.Web.UI.WebControls.ImageButton pImgBtn;
        protected global::System.Web.UI.WebControls.ListBox pListBox;
        protected global::System.Web.UI.WebControls.Table pTable;
        protected global::System.Web.UI.WebControls.Label pInnerLabel;
        protected global::System.Web.UI.WebControls.ListView pModelList;
        protected global::System.Web.UI.WebControls.DetailsView pDetails;
        protected global::System.Web.UI.WebControls.GridView pGridOds;
        protected global::System.Web.UI.WebControls.TextBox pExpando;
        protected global::System.Web.UI.WebControls.Panel pClassPanel;
        protected global::System.Web.UI.WebControls.Button pStyleBtn;
        protected global::System.Web.UI.WebControls.DataList pDataListEvt;
        protected global::System.Web.UI.WebControls.GridView pGridEvt;
        protected global::System.Web.UI.WebControls.HiddenField pHidden;
        protected global::System.Web.UI.WebControls.Image pImage;
        protected global::System.Web.UI.WebControls.Image pImageAlt;
        protected global::System.Web.UI.WebControls.RadioButton pRadioBtn1;
        protected global::System.Web.UI.WebControls.RadioButton pRadioBtn2;
        protected global::System.Web.UI.WebControls.CheckBoxList pCheckList;
        protected global::System.Web.UI.WebControls.FileUpload pFile;
        protected global::System.Web.UI.WebControls.DataList pDataListV;
        protected global::System.Web.UI.WebControls.DataList pDataListH;
        protected global::System.Web.UI.WebControls.GridView pGridFieldStyles;
        protected global::System.Web.UI.WebControls.GridView pGridAuto;
        protected global::System.Web.UI.WebControls.GridView pGridColumns;
        protected global::System.Web.UI.WebControls.FormView pFormView;
        protected global::System.Web.UI.WebControls.TextBox pReqTarget;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator pRequired;
        protected global::System.Web.UI.WebControls.TextBox pRangeTarget;
        protected global::System.Web.UI.WebControls.RangeValidator pRange;
        protected global::System.Web.UI.WebControls.ValidationSummary pSummary;
        protected global::System.Web.UI.WebControls.Button btnValidate;
        protected global::System.Web.UI.WebControls.GridView pGridStyled;
        protected global::System.Web.UI.WebControls.Panel pFieldset;
        protected global::System.Web.UI.WebControls.Label pLabelFor;
        protected global::System.Web.UI.WebControls.TextBox pNoWrap;
        protected global::System.Web.UI.WebControls.CheckBox pCheckLeft;
        protected global::System.Web.UI.WebControls.DropDownList pAppend;
        protected global::System.Web.UI.WebControls.TextBox pDynTarget;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator pRequiredDyn;
        protected global::System.Web.UI.WebControls.ValidationSummary pSummaryList;
    }
}
