//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAdmin
{
    public partial class Catalog
    {
        protected global::System.Web.UI.WebControls.GridView gvCatalog;
        protected global::System.Web.UI.WebControls.ListView lvPrices;
        protected global::System.Web.UI.WebControls.FormView fvFeatured;
    }
}
