//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAdmin
{
    public partial class Default
    {
        protected global::ProductAdmin.Controls.ProductSummary ucSummary;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.CheckBox chkInStockOnly;
        protected global::System.Web.UI.WebControls.Button btnSort;
        protected global::System.Web.UI.WebControls.GridView gvProducts;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.Repeater rptRecent;
        protected global::System.Web.UI.WebControls.HyperLink lnkNew;
    }
}
