//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAdmin
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.WebControls.Literal litSiteTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkList;
        protected global::System.Web.UI.WebControls.HyperLink lnkNew;
        protected global::System.Web.UI.WebControls.HyperLink lnkCatalog;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.Label lblFooter;
    }
}
