//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebForms
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.Button btnGreet;
        protected global::System.Web.UI.WebControls.Label lblResult;
    }
}
