//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartProbe
{
    public partial class Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.DataVisualization.Charting.Chart Sales;
        protected global::System.Web.UI.DataVisualization.Charting.Chart Saved;
    }
}