//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileProbe
{
    public partial class Default
    {
        protected global::System.Web.UI.MobileControls.Form Main;
        protected global::System.Web.UI.MobileControls.Label lblTitle;
        protected global::System.Web.UI.MobileControls.Label lblDevice;
        protected global::System.Web.UI.MobileControls.Label lblFilters;
        protected global::System.Web.UI.MobileControls.TextView txtIntro;
        protected global::System.Web.UI.MobileControls.Label lblName;
        protected global::System.Web.UI.MobileControls.TextBox txtName;
        protected global::System.Web.UI.MobileControls.RequiredFieldValidator reqName;
        protected global::System.Web.UI.MobileControls.SelectionList selSize;
        protected global::System.Web.UI.MobileControls.Command cmdGreet;
        protected global::System.Web.UI.MobileControls.Label lblResult;
        protected global::System.Web.UI.MobileControls.List lstColors;
        protected global::System.Web.UI.MobileControls.Label lblColor;
        protected global::System.Web.UI.MobileControls.Link lnkSecond;
        protected global::System.Web.UI.MobileControls.Form Second;
        protected global::System.Web.UI.MobileControls.Label lblProducts;
        protected global::System.Web.UI.MobileControls.ObjectList objProducts;
        protected global::System.Web.UI.MobileControls.Panel pnlTotal;
        protected global::System.Web.UI.MobileControls.Label lblTotal;
        protected global::System.Web.UI.MobileControls.Link lnkMain;
    }
}