//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAdmin
{
    public partial class Default
    {
        protected global::System.Web.UI.UpdatePanel upList;
        protected global::System.Web.UI.WebControls.RadioButtonList rblStatus;
        protected global::System.Web.UI.WebControls.GridView gvOrders;
        protected global::System.Web.UI.WebControls.Label lblSummary;
        protected global::System.Web.UI.UpdatePanel upSide;
        protected global::System.Web.UI.WebControls.Label lblPicked;
    }
}
