//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAdmin
{
    public partial class Detail
    {
        protected global::System.Web.UI.WebControls.Label lblCustomer;
        protected global::System.Web.UI.WebControls.Label lblProduct;
        protected global::System.Web.UI.WebControls.Label lblQuantity;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblNote;
        protected global::System.Web.UI.WebControls.Button btnShip;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    }
}
