//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAdmin
{
    public partial class Entry
    {
        protected global::System.Web.UI.WebControls.TextBox txtCustomer;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCustomer;
        protected global::System.Web.UI.WebControls.DropDownList ddlProduct;
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuantity;
        protected global::System.Web.UI.WebControls.RangeValidator rvQuantity;
        protected global::System.Web.UI.WebControls.CustomValidator cvStock;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmailConfirm;
        protected global::System.Web.UI.WebControls.CompareValidator cvEmail;
        protected global::System.Web.UI.WebControls.TextBox txtNote;
        protected global::System.Web.UI.WebControls.ValidationSummary vsEntry;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
