//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAdmin
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.ScriptManager smMain;
        protected global::System.Web.UI.WebControls.Literal litSiteTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkList;
        protected global::System.Web.UI.WebControls.HyperLink lnkEntry;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder SidePanel;
        protected global::System.Web.UI.WebControls.Label lblFooter;
    }
}
