//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitProbe
{
    public partial class Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::AjaxControlToolkit.ToolkitScriptManager sm1;
        protected global::System.Web.UI.WebControls.Label lblManager;
        protected global::System.Web.UI.UpdatePanel upGreeting;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.Button btnGreet;
        protected global::System.Web.UI.WebControls.Label lblGreeting;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlBody;
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeBody;
    }
}
